### PR TITLE
JES variations and HBB calculations

### PR DESCRIPTION
**Pull request by DylanHsu**
Remove lepton cut based ID variables from complicatedLeptons for right now; if we need then a separate analyzer macro is probably a better place for that stuff, and one is already being maintained.

Start saving the electron and muon combined isolation so it can be cut on or used in a MVA. (nominal VH analysis requires relative isolation < 0.06).

Vary the jet energy scale up and down for the H(bb) daughter jets, propagate this to the mother system, and propagate this to the regressed mass. Plot shows un regressed mass (Red=JES UP, Blue=JES DOWN, Black=Central Value JES):
http://t3serv001.mit.edu/~dhsu/github/hbbmVaried.png

Let's discuss in person before merging!

### CODE REVIEW

**Comment by DylanHsu** [comment]
Plot shows hbbm moving in the wrong direction with the JES variations, this is fixed by https://github.com/sidnarayanan/PandaAnalysis/pull/41/commits/0b84dd3a62d4c2e9f953180d09f2a2c9a3e27f05

**Comment by sidnarayanan** [comment]
Could I ask you to do me a favor and fix the two open issues (#41 and #39 ) in this PR too? If it's more trouble than I think it is, then don't bother.

**Comment by DylanHsu** [comment]
Sure why not

**Comment by sidnarayanan** [comment]
:+1: :100:

**Comment by DylanHsu** [comment]
This probably can be optimized by not performing the JES up/down variations on the data

> DEBUG   [PandaAnalyzer::Run::Time                ]: Task             GetEntry called   999 times, average time = 344.782 us, total time = 344.437 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task           initialize called   999 times, average time =  1.633 us, total time = 1.631 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task                  met called   999 times, average time =  0.996 us, total time = 0.995 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task              leptons called   999 times, average time =  3.162 us, total time = 3.159 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task              photons called   999 times, average time =  0.517 us, total time = 0.516 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task              recoils called   999 times, average time =  1.679 us, total time = 1.678 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task        fatjet basics called   999 times, average time =  0.508 us, total time = 0.508 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task               fatjet called   999 times, average time =  4.256 us, total time = 4.251 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task            H->bb jet called  2991 times, average time =  1.724 us, total time = 5.157 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task       b-jet reg info called  2991 times, average time =  1.387 us, total time = 4.148 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task                 jets called   999 times, average time = 27.905 us, total time = 27.878 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task            monohiggs called   999 times, average time = 487.206 us, total time = 486.719 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task                 taus called   999 times, average time =  0.575 us, total time = 0.574 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task     MET significance called   999 times, average time = 230.076 us, total time = 229.846 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task         gen matching called   999 times, average time =  2.885 us, total time = 2.882 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task  fatjet gen-matching called   999 times, average time =  0.524 us, total time = 0.524 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task     ak4 gen-matching called   999 times, average time =  6.690 us, total time = 6.683 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task             triggers called   999 times, average time =  8.779 us, total time = 8.770 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task      check gen infos called  1999 times, average time = 10.016 us, total time = 20.023 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task        gen leptons 2 called  1999 times, average time = 12.041 us, total time = 24.070 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task        gen neutrinos called  1999 times, average time =  0.413 us, total time = 0.825 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task    boson corrections called  1999 times, average time =  0.336 us, total time = 0.671 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task        EWK gen study called  1999 times, average time = 35.843 us, total time = 71.650 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task    qcd uncertainties called  1999 times, average time =  0.854 us, total time = 1.708 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task          gen jets nu called   999 times, average time = 12128.052 us, total time = 12115.924 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task       match gen jets called   999 times, average time = 197.020 us, total time = 196.823 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task               tt SFs called   999 times, average time =  8.866 us, total time = 8.857 ms
DEBUG   [PandaAnalyzer::Run::Time                ]: Task           photon SFs called     7 times, average time =  0.715 us, total time = 0.005 ms

**Comment by DylanHsu** [comment]
Top(bW) reconstruction for the leading loose lepton and the MET is now implemented in PandaAnalysis.
The regressed b-jet is used if the jet regression is turned on. The overall jet energy scale variations are propagated through the b-jet regression (if used) and into the top mass. 3 floats are added to GeneralTree.

Unit tests on 10k W(lv)H(bb) events:
http://t3serv001.mit.edu/~dhsu/github/topMassLep1Met.png
http://t3serv001.mit.edu/~dhsu/github/topMassLep1Met_jesUp.png
http://t3serv001.mit.edu/~dhsu/github/topMassLep1Met_jesDown.png

**Comment by DylanHsu** [comment]
Calculation of the H(bb) ellipse in eta-phi plane is added but more testing/manual checking is needed for the determination of whether soft tracks are in it.

https://github.com/sidnarayanan/PandaAnalysis/pull/41/commits/7de023b02974638259bab98671d859d84f7a7b4e

**Comment by sidnarayanan** [comment]
Is this ready for me to look at now @DylanHsu ?

**Comment by DylanHsu** [comment]
no

On Dec 29, 2017, at 8:05 PM, Sid Narayanan <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this ready for me to look at now @DylanHsu<https://github.com/dylanhsu> ?

**Comment by DylanHsu** [comment]
Small fixes for the soft activity ellipse parameterization/condition are in, ready to be merged
IsoJets are not fixed

**Pull request merged**
