### PR TITLE
Gen substructure (new PR)

### PR DESCRIPTION
**Pull request by DylanHsu**

### CODE REVIEW

**Comment by DylanHsu** [comment]
ok we are rebased to dev-rrng
now time to fix the other comments from sid

**Comment by DylanHsu** [comment]
testing right now
I think it's mostly there

**Comment by DylanHsu** [comment]
Ran test over 10,000 WH(bb) events
Plotted the most useful ECF ratio, the shape is of course slightly different but not by that much:
http://t3serv001.mit.edu/~dhsu/PandaAnalysis_on_8_0_29/Flat/test/psi022003012002.pdf
http://t3serv001.mit.edu/~dhsu/PandaAnalysis_on_8_0_29/Flat/test/genPsi022003012002.pdf
As a reference here is the balance of the reco fajet pt and the matched reclustered gen fatjet:
http://t3serv001.mit.edu/~dhsu/PandaAnalysis_on_8_0_29/Flat/test/recoGenFatjetBalance.pdf

**Comment by sidnarayanan** [comment]
It looks like this PR has diverged pretty far from the master, and not just in terms of commit history. The way we access gen particles is fairly different now. I've merged https://github.com/DylanHsu/PandaAnalysis/tree/dev-selector which should contain some of the changes, but you may want to rebase and open a PR to master. I'm closing this for now. Sorry for the mess :(

**Pull request closed without merging**
