### PR TITLE
Catch mistakes earlier

### PR DESCRIPTION
**Pull request by dabercro**
Note that I'm getting a `Could not set property complicatedPhotons` error when running `Flat/test/test.py`. But the master branch does that to me too. Cherry-picking this commit into something I had working before behaves exactly as intended.

### CODE REVIEW

**Comment by sidnarayanan** [comment]
> Note that I'm getting a Could not set property complicatedPhotons error when running Flat/test/test.py.

Sounds like you didn't re-generate dictionaries before compiling.

I'm still trying to understand why this assert is necessary - `isData` is and has always been set in a self-consistent way, based on the sample that is being read. If `isData` is wrong, then potentially everything is broken way upstream (process type, cross section, etc). How did this come up in the first place?

**Comment by dabercro** [comment]
@DylanHsu was kind enough to generate a single file for me, but didn't think to check the flag (probably because he's used to the submission framework handling it). It would be nice to avoid wasting time like that in the future.

**Comment by sidnarayanan** [comment]
Well it's just as likely he would have made any number of other configuration mistakes that can't all be checked at runtime. The testing scripts are just that - testing. It's assumed that the user doesn't make a mistake, simply because it's not possible to catch all mistakes. If he had set the wrong process type, you would have wrong k-factors. Wrong JSON leads to wrong data events. I don't like the idea of hardcoding checks for some things but leaving others wide open.

**Comment by dabercro** [comment]
I don't follow that logic at all. Checking nothing sounds like the worst possible thing you can do. My experience is that checking for mistakes you *do* know about removes those mistakes from the possible list of things one can mess up. This list will never disappear, but what's the point of keeping it large?

**Comment by sidnarayanan** [comment]
I can think of things worse than not checking for configuration mistakes... Maybe this isn't obvious, but an analysis more than just synchronization, and I have to consider that when maintaining the code. 

The design of PandaAnalysis is:

- The user defines a configuration for an analysis. 
- PandaAnalyzer reads the configuration, makes no judgement, and processes it. This is left extremely flexible to accommodate whatever the user wishes to do.

It is left completely up to the user's physics knowledge to not screw things up. I agree that we shouldn't just ignore any errors, and there is plenty of sanity-checking built into the framework. The configuration, however, is purely user-defined, and therefore I leave it to be user-checked. If a user wants to process a data file as though it is ttbar simulation, I don't see why I (or you) should get in their way.

**Pull request closed without merging**
