### PR TITLE
working on the JES uncertainty sources

### PR DESCRIPTION
**Pull request by DylanHsu**

### CODE REVIEW

**Comment by DylanHsu** [comment]
some things to think about:
- maybe there is a more intelligent way to have Up/Down for all of the individual sources, instead of https://github.com/DylanHsu/PandaAnalysis/blob/7bcf6434184116dc330c57265d853294bd4da19e/Flat/src/ModulesJets.cc#L28-L91 https://github.com/DylanHsu/PandaAnalysis/blob/7bcf6434184116dc330c57265d853294bd4da19e/Flat/interface/GeneralTree.h#L17-L60
- how do we propagate the individual JES to unclustered MET?

**Comment by sidnarayanan** [comment]
Ah oops, just noticed this PR. I have a few suggestions, will try to implement them as a PR to your branch. I

**Comment by DylanHsu** [comment]
Who needs to do what for this?

**Comment by sidnarayanan** [comment]
This is now being tracked in #88 , so closing.

**Pull request closed without merging**
