### PR TITLE
VH: MET significance, electron MVA WP's, high quality track flag for soft activity

### PR DESCRIPTION
**Pull request by DylanHsu**
Needs testing before merge
Also need to hear back from Benedikt about the lepton minimum fakeable object definitions in Z(vv)H

### CODE REVIEW

**Comment by DylanHsu** [comment]
validating electron mva on W(l+v)H(bb) 009 file
```
root [6] events->Scan(Form("electronPt:(electronSelBit&%d)!=0:(electronSelBit&%d)!=0",PandaAnalyzer::kEleMvaWP90,PandaAnalyzer::kEleMvaWP80),"nLooseElectron==1")
***********************************************************
*    Row   * Instance * electronP * (electron * (electron *
***********************************************************
*        3 *        0 * 32.207428 *         1 *         1 *
*        4 *        0 * 244.78385 *         1 *         1 *
*        6 *        0 * 60.908809 *         1 *         1 *
*        8 *        0 * 10.071505 *         0 *         0 *
*       13 *        0 * 105.93553 *         1 *         1 *
*       14 *        0 * 54.591461 *         1 *         1 *
*       23 *        0 * 42.307792 *         0 *         0 *
*       25 *        0 * 44.612491 *         1 *         1 *
*       26 *        0 * 25.093462 *         1 *         1 *
*       28 *        0 * 10.738734 *         0 *         0 *
*       31 *        0 * 86.398666 *         1 *         1 *
*       36 *        0 * 48.875419 *         1 *         1 *
*       51 *        0 * 155.76747 *         1 *         1 *
*       53 *        0 * 48.486896 *         1 *         1 *
*       54 *        0 * 20.458051 *         1 *         1 *
*       55 *        0 * 96.591438 *         1 *         1 *
*       58 *        0 * 23.481479 *         1 *         0 *
*       59 *        0 * 86.841156 *         1 *         1 *
*       64 *        0 * 31.500724 *         1 *         1 *
*       66 *        0 * 58.965087 *         1 *         1 *
*       69 *        0 * 60.696319 *         1 *         1 *
*       87 *        0 * 20.710222 *         1 *         1 *
*       92 *        0 * 33.764648 *         1 *         1 *
*       93 *        0 * 30.950346 *         1 *         1 *
*       97 *        0 * 149.56794 *         1 *         1 *
*      104 *        0 * 71.583457 *         1 *         1 *
*      115 *        0 * 10.851600 *         0 *         0 *
*      117 *        0 * 79.503936 *         1 *         1 *
*      120 *        0 * 79.752861 *         1 *         1 *
*      121 *        0 * 19.583442 *         1 *         1 *
*      126 *        0 * 54.810043 *         1 *         1 *
*      127 *        0 * 31.036539 *         1 *         1 *
*      128 *        0 * 40.080757 *         0 *         0 *
*      130 *        0 * 36.621181 *         1 *         1 *
*      143 *        0 * 134.56416 *         1 *         1 *
*      150 *        0 * 38.598945 *         1 *         1 *
*      154 *        0 * 47.411632 *         1 *         1 *
*      155 *        0 * 22.755228 *         1 *         1 *
*      158 *        0 * 46.305938 *         1 *         0 *
*      162 *        0 * 105.38992 *         1 *         1 *
*      164 *        0 * 121.77550 *         1 *         1 *
*      171 *        0 * 130.80902 *         1 *         1 *
*      172 *        0 * 151.95555 *         1 *         0 *
*      192 *        0 * 65.440231 *         1 *         1 *
*      195 *        0 * 34.062706 *         1 *         0 *
*      211 *        0 * 152.26489 *         1 *         0 *
*      213 *        0 * 43.388782 *         1 *         1 *
*      214 *        0 * 26.288084 *         1 *         1 *
*      218 *        0 * 10.117892 *         0 *         0 *
*      220 *        0 * 32.002014 *         1 *         1 *
```

**Comment by DylanHsu** [comment]
validating soft activity variables (with the ellipse parameters not changed at all) just requiring the high quality track flag

```
root [8] events->Scan("nSoft2:nSoft5:nSoft10:sumEtSoft1")
************************************************************
*    Row   *    nSoft2 *    nSoft5 *   nSoft10 * sumEtSoft *
************************************************************
*        0 *        11 *         4 *         0 * 52.094047 *
*        1 *         3 *         0 *         0 * 21.783489 *
*        2 *         4 *         0 *         0 * 29.261552 *
*        3 *         8 *         3 *         2 * 82.356041 *
*        4 *         2 *         1 *         0 * 14.175346 *
*        5 *        10 *         2 *         1 * 58.640766 *
*        6 *         5 *         2 *         1 * 45.129478 *
*        7 *        16 *         4 *         1 * 84.448318 *
*        8 *         2 *         1 *         1 * 94.525848 *
*        9 *         5 *         2 *         1 * 44.332473 *
*       10 *        -1 *        -1 *        -1 *        -1 *
*       11 *        -1 *        -1 *        -1 *        -1 *
*       12 *         7 *         2 *         1 * 54.159942 *
*       13 *         1 *         0 *         0 * 5.8106894 *
*       14 *         1 *         0 *         0 * 7.5294709 *
*       15 *         4 *         1 *         1 * 32.825737 *
*       16 *         5 *         3 *         3 * 204.92001 *
*       17 *        -1 *        -1 *        -1 *        -1 *
*       18 *        -1 *        -1 *        -1 *        -1 *
*       19 *         1 *         1 *         0 * 21.390567 *
*       20 *         4 *         1 *         0 * 22.510887 *
*       21 *        -1 *        -1 *        -1 *        -1 *
*       22 *         1 *         1 *         1 * 25.421463 *
*       23 *        -1 *        -1 *        -1 *        -1 *
*       24 *        -1 *        -1 *        -1 *        -1 *
*       25 *         9 *         5 *         1 * 61.791397 *
*       26 *        17 *         6 *         1 * 91.535186 *
*       27 *         0 *         0 *         0 * 8.2105627 *
*       28 *        -1 *        -1 *        -1 *        -1 *
*       29 *         1 *         1 *         1 * 20.532629 *
*       30 *         5 *         1 *         0 * 27.951503 *
*       31 *         4 *         1 *         0 * 29.809625 *
*       32 *         6 *         3 *         2 * 68.008117 *
*       33 *        10 *         5 *         3 * 207.88485 *
*       34 *         8 *         5 *         3 * 72.282821 *
*       35 *        -1 *        -1 *        -1 *        -1 *
*       36 *         4 *         2 *         0 * 26.303682 *
*       37 *         3 *         0 *         0 * 17.405662 *
*       38 *         7 *         1 *         1 * 47.835193 *
*       39 *        -1 *        -1 *        -1 *        -1 *
*       40 *         2 *         1 *         1 * 21.610487 *
*       41 *         8 *         5 *         2 * 176.29124 *
*       42 *         1 *         1 *         1 * 84.392715 *
*       43 *        -1 *        -1 *        -1 *        -1 *
*       44 *        -1 *        -1 *        -1 *        -1 *
*       45 *         7 *         4 *         1 * 78.024223 *
*       46 *         6 *         2 *         1 * 41.148567 *
*       47 *        -1 *        -1 *        -1 *        -1 *
*       48 *         7 *         2 *         0 * 36.319919 *
*       49 *        11 *         2 *         1 * 92.795974 *
Type <CR> to continue or q to quit ==> q     
************************************************************
(Long64_t) 50
root [9] events->Scan("nSoft2:nSoft5:nSoft10:sumEtSoft1","sumEtSoft1>0")
************************************************************
*    Row   *    nSoft2 *    nSoft5 *   nSoft10 * sumEtSoft *
************************************************************
*        0 *        11 *         4 *         0 * 52.094047 *
*        1 *         3 *         0 *         0 * 21.783489 *
*        2 *         4 *         0 *         0 * 29.261552 *
*        3 *         8 *         3 *         2 * 82.356041 *
*        4 *         2 *         1 *         0 * 14.175346 *
*        5 *        10 *         2 *         1 * 58.640766 *
*        6 *         5 *         2 *         1 * 45.129478 *
*        7 *        16 *         4 *         1 * 84.448318 *
*        8 *         2 *         1 *         1 * 94.525848 *
*        9 *         5 *         2 *         1 * 44.332473 *
*       12 *         7 *         2 *         1 * 54.159942 *
*       13 *         1 *         0 *         0 * 5.8106894 *
*       14 *         1 *         0 *         0 * 7.5294709 *
*       15 *         4 *         1 *         1 * 32.825737 *
*       16 *         5 *         3 *         3 * 204.92001 *
*       19 *         1 *         1 *         0 * 21.390567 *
*       20 *         4 *         1 *         0 * 22.510887 *
*       22 *         1 *         1 *         1 * 25.421463 *
*       25 *         9 *         5 *         1 * 61.791397 *
*       26 *        17 *         6 *         1 * 91.535186 *
*       27 *         0 *         0 *         0 * 8.2105627 *
*       29 *         1 *         1 *         1 * 20.532629 *
*       30 *         5 *         1 *         0 * 27.951503 *
*       31 *         4 *         1 *         0 * 29.809625 *
*       32 *         6 *         3 *         2 * 68.008117 *
*       33 *        10 *         5 *         3 * 207.88485 *
*       34 *         8 *         5 *         3 * 72.282821 *
*       36 *         4 *         2 *         0 * 26.303682 *
*       37 *         3 *         0 *         0 * 17.405662 *
*       38 *         7 *         1 *         1 * 47.835193 *
*       40 *         2 *         1 *         1 * 21.610487 *
*       41 *         8 *         5 *         2 * 176.29124 *
*       42 *         1 *         1 *         1 * 84.392715 *
*       45 *         7 *         4 *         1 * 78.024223 *
*       46 *         6 *         2 *         1 * 41.148567 *
*       48 *         7 *         2 *         0 * 36.319919 *
*       49 *        11 *         2 *         1 * 92.795974 *
*       50 *         1 *         0 *         0 * 4.2610631 *
*       51 *         7 *         0 *         0 * 37.640552 *
*       53 *         6 *         1 *         1 * 54.252246 *
*       54 *         7 *         3 *         0 * 47.473972 *
*       55 *         7 *         3 *         1 * 81.416488 *
*       56 *         4 *         1 *         0 * 23.601652 *
*       58 *         2 *         1 *         0 * 11.744993 *
*       59 *         4 *         2 *         1 * 59.011184 *
*       60 *         7 *         2 *         2 * 84.987625 *
*       61 *         3 *         0 *         0 * 18.144329 *
*       62 *         9 *         1 *         0 * 53.458683 *
*       63 *         2 *         0 *         0 * 22.246784 *
*       64 *         3 *         3 *         1 * 33.191616 *
```

**Comment by DylanHsu** [comment]
validating soft activity variables (with the ellipse parameters not changed at all) just requiring the high quality track flag
```
root [10] events->Scan("nSoft2:nSoft5:nSoft10:sumEtSoft1","sumEtSoft1>0")
************************************************************
*    Row   *    nSoft2 *    nSoft5 *   nSoft10 * sumEtSoft *
************************************************************
*        0 *        11 *         4 *         0 * 52.094047 *
*        1 *         3 *         0 *         0 * 21.783489 *
*        2 *         4 *         0 *         0 * 29.261552 *
*        3 *         8 *         3 *         2 * 82.356041 *
*        4 *         2 *         1 *         0 * 14.175346 *
*        5 *        10 *         2 *         1 * 58.640766 *
*        6 *         5 *         2 *         1 * 45.129478 *
*        7 *        16 *         4 *         1 * 84.448318 *
*        8 *         2 *         1 *         1 * 94.525848 *
*        9 *         5 *         2 *         1 * 44.332473 *
*       12 *         7 *         2 *         1 * 54.159942 *
*       13 *         1 *         0 *         0 * 5.8106894 *
*       14 *         1 *         0 *         0 * 7.5294709 *
*       15 *         4 *         1 *         1 * 32.825737 *
*       16 *         5 *         3 *         3 * 204.92001 *
*       19 *         1 *         1 *         0 * 21.390567 *
*       20 *         4 *         1 *         0 * 22.510887 *
*       22 *         1 *         1 *         1 * 25.421463 *
*       25 *         9 *         5 *         1 * 61.791397 *
*       26 *        17 *         6 *         1 * 91.535186 *
*       27 *         0 *         0 *         0 * 8.2105627 *
*       29 *         1 *         1 *         1 * 20.532629 *
*       30 *         5 *         1 *         0 * 27.951503 *
*       31 *         4 *         1 *         0 * 29.809625 *
*       32 *         6 *         3 *         2 * 68.008117 *
*       33 *        10 *         5 *         3 * 207.88485 *
*       34 *         8 *         5 *         3 * 72.282821 *
*       36 *         4 *         2 *         0 * 26.303682 *
*       37 *         3 *         0 *         0 * 17.405662 *
*       38 *         7 *         1 *         1 * 47.835193 *
*       40 *         2 *         1 *         1 * 21.610487 *
*       41 *         8 *         5 *         2 * 176.29124 *
*       42 *         1 *         1 *         1 * 84.392715 *
*       45 *         7 *         4 *         1 * 78.024223 *
*       46 *         6 *         2 *         1 * 41.148567 *
*       48 *         7 *         2 *         0 * 36.319919 *
*       49 *        11 *         2 *         1 * 92.795974 *
*       50 *         1 *         0 *         0 * 4.2610631 *
*       51 *         7 *         0 *         0 * 37.640552 *
*       53 *         6 *         1 *         1 * 54.252246 *
*       54 *         7 *         3 *         0 * 47.473972 *
*       55 *         7 *         3 *         1 * 81.416488 *
*       56 *         4 *         1 *         0 * 23.601652 *
*       58 *         2 *         1 *         0 * 11.744993 *
*       59 *         4 *         2 *         1 * 59.011184 *
*       60 *         7 *         2 *         2 * 84.987625 *
*       61 *         3 *         0 *         0 * 18.144329 *
*       62 *         9 *         1 *         0 * 53.458683 *
*       63 *         2 *         0 *         0 * 22.246784 *
*       64 *         3 *         3 *         1 * 33.191616 *
```

**Comment by DylanHsu** [comment]
validating the actual pfmet significance and puppi met significance
distributions look like they are correct for signal

http://t3serv001.mit.edu/~dhsu/PandaAnalysis_on_8_0_29/Flat/test/pfmetsig_009_wlnhbb.pdf
http://t3serv001.mit.edu/~dhsu/PandaAnalysis_on_8_0_29/Flat/test/puppimetsig_009_wlnhbb.pdf

```
root [12] events->Scan("nJet:pfmet:pfmetphi:pfmetsig:puppimetsig")
************************************************************************
*    Row   *      nJet *     pfmet *  pfmetphi *  pfmetsig * puppimets *
************************************************************************
*        0 *         2 * 50.245048 * -1.045860 * 4.8176102 * 11.100263 *
*        1 *         2 * 71.740974 * -0.924167 * 10.134517 *  11.53057 *
*        2 *         2 * 21.610849 * 2.4990062 * 0.7860704 * 16.452640 *
*        3 *         4 * 71.926063 * 0.6723899 * 12.011059 * 28.679449 *
*        4 *         2 * 43.432727 * 0.2183856 * 8.8731603 * 208.49598 *
*        5 *         2 * 59.020591 * 0.8309036 * 7.3477869 * 50.615345 *
*        6 *         3 * 85.451484 * 0.6371578 * 18.217628 * 117.18054 *
*        7 *         2 * 39.548301 * 0.6303158 * 3.4953503 * 9.3501033 *
*        8 *         6 * 54.812767 * 1.9718172 * 3.3733487 * 142.00036 *
*        9 *         3 * 87.809875 * 1.5481655 * 19.232650 * 21.738308 *
*       10 *         1 * 42.994274 * -0.637313 * 4.6368103 * 43.701248 *
*       11 *         0 * 41.579689 * -2.946896 * 4.4250855 * 15.361597 *
*       12 *         5 * 138.58725 * 2.5897505 * 40.254535 * 111.36283 *
*       13 *         2 * 195.78413 * -2.497134 * 97.022438 * 166.63233 *
*       14 *         2 * 5.4422593 * -0.549535 * 0.0675761 * 23.184921 *
*       15 *         3 * 29.872089 * -1.034319 * 1.5169600 * 4.3201923 *
*       16 *         5 * 143.06158 * 2.0778868 * 33.088432 * 44.272743 *
*       17 *         1 * 19.866537 * 1.7926391 * 0.6563481 * 9.3376522 *
*       18 *         1 * 57.940647 * -2.535377 * 4.4401807 * 19.230468 *
*       19 *         2 * 43.678607 * -0.923705 * 3.3811197 * 6.0624165 *
*       20 *         3 * 4.7355327 * 1.8199284 * 0.0872473 * 0.1870808 *
*       21 *         1 * 92.361702 * -1.502380 * 15.175236 * 37.778518 *
*       22 *         3 * 68.528404 * -1.717876 * 6.7232084 * 5.0645685 *
*       23 *         1 * 33.707389 * -1.522298 * 1.4982553 * 1.1313065 *
*       24 *         0 * 33.483764 * -0.513379 * 3.5635352 * 165.95826 *
*       25 *         2 *   81.5737 * -1.574841 * 10.598330 * 24.037780 *
*       26 *         3 * 42.356452 * 3.0811739 * 3.9102675 * 0.1249483 *
*       27 *         3 * 54.674072 * -1.949488 * 4.1368880 * 34.542182 *
*       28 *         0 * 144.87367 * 2.1256451 * 67.862754 * 505.02804 *
*       29 *         3 * 81.417427 * 2.1221168 * 14.495417 * 24.669940 *
*       30 *         2 * 78.467445 * -1.765092 * 6.4924855 * 30.110303 *
*       31 *         2 * 62.744113 * 2.9192800 * 3.9791486 * 8.8231096 *
*       32 *         4 * 95.301841 * 0.4928033 * 18.837680 * 73.568603 *
*       33 *         4 * 115.26558 * 1.7657142 * 21.324266 * 94.298652 *
*       34 *         6 * 91.502067 * 0.5121822 * 10.301676 * 55.789878 *
*       35 *         0 * 61.416679 * 0.4378894 * 8.4534740 * 109.19429 *
*       36 *         3 * 61.635318 * 0.1833598 * 8.3149290 * 22.741895 *
*       37 *         2 * 53.463623 * 3.0439221 * 4.3129320 * 15.450175 *
*       38 *         3 *  16.29603 * 1.1361495 * 0.5603593 * 14.659009 *
*       39 *         1 * 48.804660 * -1.625258 * 6.2951006 * 29.181987 *
*       40 *         3 * 88.561317 * 1.2464903 * 16.484617 * 133.25293 *
*       41 *         5 * 82.949935 * 0.2330290 * 9.8061981 * 9.8802995 *
*       42 *         3 * 102.62679 * -0.091908 * 18.167953 * 31.995809 *
*       43 *         1 * 43.361564 * -2.813362 * 2.1908130 * 7.9096655 *
*       44 *         0 * 41.834133 * 2.4192066 * 7.0513758 * 22.346937 *
*       45 *         3 * 53.616466 * -1.628284 * 5.6811871 * 33.290596 *
*       46 *         4 * 23.701211 * 1.8524988 * 1.2930657 * 1.6777064 *
*       47 *         1 * 63.894725 * -1.002543 * 8.4761362 * 5.4073901 *
*       48 *         3 * 69.842712 * -0.028864 * 6.4437685 * 100.91009 *
*       49 *         3 * 100.58730 * 0.9157046 * 26.797534 * 258.48474 *
```

**Comment by DylanHsu** [comment]
Please review and merge

**Comment by sidnarayanan** [comment]
I've merged this branch into https://github.com/sidnarayanan/PandaAnalysis/tree/branch-merge. I've opened https://github.com/GuillelmoGomezCeballos/PandaAnalysis/pull/3 from branch-merge to G's master. Once that's merged, I'll merge https://github.com/sidnarayanan/PandaAnalysis/pull/59. I figure this is the most complicated and error-prone way to do things.

**Pull request merged**
